import { ItipFin } from './tip_fin.model';
import { IMacroProg } from './macro_prog.model';
import { IProMun } from './promun.model';
import { IProtem } from './protem.model';
import { IBan } from './bando.model';
import { IStaPro } from './stapro.model';
import { IStaFin } from './stafin.model';
import { IProNil } from './pronil.model';

export interface IProg {
  risorse?: any;
  infAgg?: any;
  risorseDiCui?: any;
  risorseLivelloBasso?: any;
  cntlivinf: number;
  codappren: string;
  codass: string;
  codcig: string;
  codcup: string;
  codcui: string;
  codgami: string;
  codpro: string;
  codset: string;
  codtippro: string;
  delcan: string;
  desaffhou: string;
  despro: string;
  estaff: string;
  flgopeavv: string;
  id: number;
  idBan?: number;
  idDir?: number;
  idMacpro?: number;
  idMun?: number;
  idNil?: number;
  idPropad?: number;
  idStafin?: number;
  idStapro?: number;
  idTem?: number;
  idTipfin?: number;
  iddecpro: string;
  impaccpre: number;
  impigv: number;
  impigvdel: number;
  impimppre: number;
  impimpric: number;
  impmanpre: number;
  imprevpre: number;
  livpro: number;
  nil?: number;
  notaff?: string;
  notigv?: string;
  notimp: string;
  notpre: string;
  notpro: string;
  rifigv: string;
  tippro: string;
  veraff: string;
  proTipfinByIdTipfin: ItipFin;
  proMacproByIdMacpro: IMacroProg;
  proStaproByIdStapro: IStaPro;
  proStafinByIdStafin: IStaFin;
  proBanByIdBan: IBan;
  proDetconsById: any;
  proTemByIdTem: IProtem;
  proMunByIdMun: IProMun;
  proNilByIdNil: IProNil;
}
